### ISSUE TITLE
Error when running deploy

### ISSUE THREAD

**Issue by KevinSHansen** [aws-samples/php-examples-for-aws-lambda#16]
Hi, when im trying to deploy this using SAM im running into a problem.

I have done following:
- Cloned your repository
- Installed AWS CLI and AWS SAM

aws --version:
aws-cli/2.0.52 Python/3.7.4 Darwin/19.6.0 exe/x86_64

sam --version:
SAM CLI, version 1.3.2

When i run "sam deploy -g" i get this error:
`Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.3.2', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 198, in cli
    config_env,
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 248, in do_cli
    guided_context.run()
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 199, in run
    self.guided_prompts(_parameter_override_keys)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 115, in guided_prompts
    self.prompt_authorization(sanitize_parameter_overrides(input_parameter_overrides))
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 151, in prompt_authorization
    auth_required_per_resource = auth_per_resource(parameter_overrides, get_template_data(self.template_file))
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/auth_utils.py", line 39, in auth_per_resource
    _auth_resource_event(sam_functions, sam_function, _auth_per_resource)
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/auth_utils.py", line 68, in _auth_resource_event
    elif _auth_id(sam_functions.resources, event.get("Properties", {}), identifier):
  File "/usr/local/Cellar/aws-sam-cli/1.3.2/libexec/lib/python3.7/site-packages/samcli/commands/deploy/auth_utils.py", line 93, in _auth_id
    api_resource = resources_dict.get(resource_name, {})
TypeError: unhashable type: 'dict'`

**Comment by bls20AWS** [comment]
Hi Kevin, which template are you running `sam deploy -g`  on?

**Comment by markusgulden** [comment]
For me, the issue occurred withthe template of 0.3-Replacing-The-HTTP-Web-Server-For-Traditional-PHP-Frameworks/

**Comment by bls20AWS** [comment]
Thanks fellas! I found a couple of little typos in the SAM template that was causing the deployment error. Have fixed and updated. You should be good to go now.
